// Express Billing - matches express.php columns
export const expressBillingData = [
  {
    id: 1,
    exp: "EXP-2024-001",
    date: "2025-11-20",
    assignedArea: "Metro Manila",
    plateNo: "AAG-1234",
    driver: "Juan Dela Cruz",
    courier: "Express Courier",
    truckType: "L300",
    unitPriceCharges: 5500,
    additionalCourier: 500,
    additionalServiceFee: 200,
    regularSpecialHoliday: 0,
    deductionFuel: 300,
    hiringDriverCourier: 0,
    grandTotal: 5900,
    parkingFeeEntranceFee: 150,
    byod: 100,
    remarks: "Delivered on time",
    reimbursementOfficialReceipt: "OR-12345",
  },
  {
    id: 2,
    exp: "EXP-2024-002",
    date: "2025-11-18",
    assignedArea: "Cavite",
    plateNo: "AB4-5678",
    driver: "Pedro Santos",
    courier: "Fast Delivery",
    truckType: "Canter",
    unitPriceCharges: 8500,
    additionalCourier: 800,
    additionalServiceFee: 300,
    regularSpecialHoliday: 500,
    deductionFuel: 500,
    hiringDriverCourier: 200,
    grandTotal: 9800,
    parkingFeeEntranceFee: 250,
    byod: 150,
    remarks: "Rush delivery",
    reimbursementOfficialReceipt: "OR-12346",
  },
  {
    id: 3,
    exp: "EXP-2024-003",
    date: "2025-11-15",
    assignedArea: "Laguna",
    plateNo: "AKA-9012",
    driver: "Maria Garcia",
    courier: "Speed Courier",
    truckType: "Elf",
    unitPriceCharges: 12000,
    additionalCourier: 1000,
    additionalServiceFee: 500,
    regularSpecialHoliday: 0,
    deductionFuel: 700,
    hiringDriverCourier: 0,
    grandTotal: 12800,
    parkingFeeEntranceFee: 350,
    byod: 200,
    remarks: "Bulk delivery",
    reimbursementOfficialReceipt: "OR-12347",
  },
]

// Forward Billing - matches forward.php columns
export const forwardBillingData = [
  {
    id: 1,
    seriesNo: "FWD-2024-001",
    date: "2025-11-20",
    plateNo: "AAG-1234",
    driver: "Juan Dela Cruz",
    courier: "Forward Express",
    truckType: "10 Wheeler",
    unitPriceCharge: 15000,
    additionalCourierOBC: 1500,
    grandTotal: 16500,
    tollAndParking: 800,
    byod: 500,
    remarks: "Long haul delivery",
  },
  {
    id: 2,
    seriesNo: "FWD-2024-002",
    date: "2025-11-18",
    plateNo: "AB4-5678",
    driver: "Pedro Santos",
    courier: "Cargo Forward",
    truckType: "6 Wheeler",
    unitPriceCharge: 12000,
    additionalCourierOBC: 1200,
    grandTotal: 13200,
    tollAndParking: 600,
    byod: 400,
    remarks: "Provincial delivery",
  },
  {
    id: 3,
    seriesNo: "FWD-2024-003",
    date: "2025-11-15",
    plateNo: "AKA-9012",
    driver: "Maria Garcia",
    courier: "Heavy Cargo",
    truckType: "10 Wheeler",
    unitPriceCharge: 22000,
    additionalCourierOBC: 2000,
    grandTotal: 24000,
    tollAndParking: 1200,
    byod: 700,
    remarks: "Heavy load",
  },
]

// Motorcycle Billing - matches motorcycle.php columns
export const motorcycleBillingData = [
  {
    id: 1,
    mcId: "MC-2024-001",
    date: "2025-11-20",
    portCode: "MNL-001",
    driver: "Juan Dela Cruz",
    couriersCode: "MC-JDC-001",
    manifestNoFeOfd: "MAN-12345",
    supplierName: "Shopee",
    fleetType: "Motorcycle",
    serviceType1: "Delivery",
    serviceType: "Standard",
    deliveryPickupCostTrip: 350,
    overtime: 50,
    byodLoadAllowance: 100,
    gasSubsidy20: 80,
    excessIncentives: 0,
    totalFinalCost: 580,
  },
  {
    id: 2,
    mcId: "MC-2024-002",
    date: "2025-11-19",
    portCode: "MNL-002",
    driver: "Pedro Santos",
    couriersCode: "MC-PS-002",
    manifestNoFeOfd: "MAN-12346",
    supplierName: "Lazada",
    fleetType: "Motorcycle",
    serviceType1: "Pick-up",
    serviceType: "Express",
    deliveryPickupCostTrip: 450,
    overtime: 100,
    byodLoadAllowance: 120,
    gasSubsidy20: 90,
    excessIncentives: 50,
    totalFinalCost: 810,
  },
  {
    id: 3,
    mcId: "MC-2024-003",
    date: "2025-11-18",
    portCode: "MNL-003",
    driver: "Maria Garcia",
    couriersCode: "MC-MG-003",
    manifestNoFeOfd: "MAN-12347",
    supplierName: "J&T Express",
    fleetType: "Motorcycle",
    serviceType1: "Delivery",
    serviceType: "COD",
    deliveryPickupCostTrip: 380,
    overtime: 0,
    byodLoadAllowance: 90,
    gasSubsidy20: 75,
    excessIncentives: 30,
    totalFinalCost: 575,
  },
]

export const expressInvoices = expressBillingData
export const forwardInvoices = forwardBillingData
export const motorcycleInvoices = motorcycleBillingData

export const billingStats = [
  { title: "Total Revenue", value: "₱284,500", change: "+18.3%" },
  { title: "Outstanding", value: "₱49,450", change: "-5.2%" },
  { title: "Overdue", value: "₱8,750", change: "+2.1%" },
  { title: "This Month", value: "₱111,850", change: "+12.7%" },
]
