export const vehicles = [
  {
    id: "TRK-001",
    name: "Truck Alpha",
    type: "Heavy Truck",
    plateNumber: "ABC-1234",
    status: "active",
    driver: "John Doe",
    mileage: 125000,
    lastService: "2025-10-15",
  },
  {
    id: "TRK-002",
    name: "Truck Beta",
    type: "Heavy Truck",
    plateNumber: "DEF-5678",
    status: "active",
    driver: "Jane Smith",
    mileage: 98000,
    lastService: "2025-11-01",
  },
  {
    id: "TRK-003",
    name: "Van Charlie",
    type: "Delivery Van",
    plateNumber: "GHI-9012",
    status: "maintenance",
    driver: "Mike Johnson",
    mileage: 75000,
    lastService: "2025-09-20",
  },
  {
    id: "TRK-004",
    name: "Truck Delta",
    type: "Heavy Truck",
    plateNumber: "JKL-3456",
    status: "active",
    driver: "Sarah Williams",
    mileage: 156000,
    lastService: "2025-10-28",
  },
  {
    id: "TRK-005",
    name: "Van Echo",
    type: "Delivery Van",
    plateNumber: "MNO-7890",
    status: "active",
    driver: "Chris Brown",
    mileage: 62000,
    lastService: "2025-11-10",
  },
  {
    id: "TRK-006",
    name: "Truck Foxtrot",
    type: "Light Truck",
    plateNumber: "PQR-2345",
    status: "inactive",
    driver: null,
    mileage: 210000,
    lastService: "2025-08-05",
  },
]

export const vehicleStats = [
  { title: "Total Fleet", value: "45", change: "+3" },
  { title: "Active Vehicles", value: "38", change: "+2" },
  { title: "In Maintenance", value: "5", change: "-1" },
  { title: "Inactive", value: "2", change: "0" },
]
