export const deliveryStatusMap = {
  1: "Preparing",
  2: "In Transit",
  3: "Delivered",
  4: "Cancelled",
  5: "Rescheduled",
}

export const deliveryStatusOptions = [
  { value: "0", label: "All" },
  { value: "1", label: "Preparing" },
  { value: "2", label: "In Transit" },
  { value: "3", label: "Delivered" },
  { value: "4", label: "Cancelled" },
  { value: "5", label: "Rescheduled" },
]

export const payModeOptions = [
  { value: "cash", label: "Cash" },
  { value: "card", label: "Card" },
  { value: "bank_transfer", label: "Bank Transfer" },
  { value: "cheque", label: "Cheque" },
  { value: "cod", label: "Cash on Delivery" },
]

export const deliveryCategoryOptions = [
  { value: "document", label: "Document" },
  { value: "parcel", label: "Parcel" },
  { value: "cargo", label: "Cargo" },
  { value: "electronics", label: "Electronics" },
]

export const deliveries = [
  {
    id: 1,
    trackingNo: "JANFRANS2512130001",
    createdAt: "2025-12-13",
    shipperName: "Global Tech Supplies",
    consigneeName: "ABC Corporation",
    totalAmount: "1500.00",
    payMode: "cod",
    chargeableWeight: "2.5",
    deliveryCategory: "parcel",
    deliveryStatus: 3,
    attemptCount: 1,
    remarks: "Received by guard",
    estimatedTime: "2025-12-13 14:30:00", // For 'Delivered' column
    latitude: "14.5547", // For 'Location' column
    longitude: "121.0244",
  },
  {
    id: 2,
    trackingNo: "JANFRANS2512130002",
    createdAt: "2025-12-13",
    shipperName: "Lazada Logistics",
    consigneeName: "Juan Dela Cruz",
    totalAmount: "0.00",
    payMode: "card",
    chargeableWeight: "0.5",
    deliveryCategory: "document",
    deliveryStatus: 2,
    attemptCount: 0,
    remarks: "",
    estimatedTime: "",
    latitude: "14.6760",
    longitude: "121.0437",
  },
  {
    id: 3,
    trackingNo: "JANFRANS2512130003",
    createdAt: "2025-12-12",
    shipperName: "Shopee Xpress",
    consigneeName: "Maria Clara",
    totalAmount: "550.50",
    payMode: "cod",
    chargeableWeight: "1.0",
    deliveryCategory: "parcel",
    deliveryStatus: 1,
    attemptCount: 0,
    remarks: "Pending pickup",
    estimatedTime: null,
    latitude: "14.5764",
    longitude: "121.0851",
  },
  {
    id: 4,
    trackingNo: "JANFRANS2512130004",
    createdAt: "2025-12-12",
    shipperName: "Office Warehouse",
    consigneeName: "Tech Solutions Inc.",
    totalAmount: "12500.00",
    payMode: "cheque",
    chargeableWeight: "15.0",
    deliveryCategory: "cargo",
    deliveryStatus: 4,
    attemptCount: 2,
    remarks: "Client refused",
    estimatedTime: null,
    latitude: "14.5176",
    longitude: "121.0509",
  },
  {
    id: 5,
    trackingNo: "JANFRANS2512130005",
    createdAt: "2025-12-11",
    shipperName: "Zalora",
    consigneeName: "Fashion Hub",
    totalAmount: "2300.00",
    payMode: "bank_transfer",
    chargeableWeight: "3.2",
    deliveryCategory: "parcel",
    deliveryStatus: 5,
    attemptCount: 1,
    remarks: "Rainy weather",
    estimatedTime: "2025-12-14 09:00:00",
    latitude: "14.6507",
    longitude: "121.1029",
  },
]